import "./globals.css";
import { Exo } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const exo = Exo({ subsets: ["latin"] });
export const metadata = {
  title: "MoodAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={exo.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
